spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    # password: 123456
    # Number of ms to wait before throwing an exception if no connection is available.
    max-wait: 10000
    # Maximum number of active connections that can be allocated from this pool at the same time.
    max-active: 20

elasticsearch:
  cluster:
    name: DESKTOP-2AUKON6
  host: 127.0.0.1
  port: 9300